default:
  before_script:
    - python --version
    - pip install -e ".[dev]"

stages:
  - static_analysis
  - test
  - docs

flake8:
  stage: static_analysis
  image: "python:3.11"
  script:
    - flake8 gunc/
  rules:
    - if: $CI_COMMIT_BRANCH != "docs"

unit_test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9", "3.10", "3.11"]
  image: "python:${PYTHON_VERSION}"
  script:
    - pytest -m "not integration"
  rules:
    - if: $CI_COMMIT_BRANCH != "docs"

coverage:
  stage: test
  image: "python:3.11"
  script:
    - coverage run -m pytest -m "not integration"
    - coverage report -m
    - coverage xml -o coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.*\s+(\d+%)$/'
  rules:
    - if: $CI_COMMIT_BRANCH != "docs"

pages:
  stage: docs
  image: "python:3.11"
  before_script:
    - pip install -e ".[docs]"
  script:
    - make -C docs html
    - mkdir public
    - mv docs/build/html/* ./public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "docs"
